config/routes.rb
Printless::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles, has_many: :comments
  resources :projects, has_many: :comments
  resources :relationships, only: [:create, :destroy]
  resources :invitation_lists, only: [:new, :create]
  

  match '/changepassword', to: 'users#change_password'
  #Change back for live version
  match '/signup',  to: 'users#new'
  #match '/signup', to: 'invitation_lists#temphome'
  match '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  match '/contact', to: 'mostly_static_pages#contact'
  match '/about', to: 'mostly_static_pages#about'

  root :to => 'invitation_lists#temphome'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :about_me, :twitter_id, :interests,
                  :password, :password_confirmation, :journalist, :image
  has_secure_password

  mount_uploader :image, ImageUploader
  
  has_many :projects, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  #has_many :donations
  
  #has_many :benefactors, through: :donations, source: :donatee
  
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:    :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: valid_email_regex },
                    uniqueness: { case_sensitive: false }

#Fix this to work for update#
#validates :password, length: { minimum: 6 }
  
  
  def following?(other_user)
    self.relationships.find_by_followed_id(other_user.id)
  end
  
  def follow!(other_user)
    self.relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
  
  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :following, :followers]
  before_filter :current_user,   only: [:edit, :update, :destroy]
  before_filter :admin_user,     only: :destroy

  def change_password
    @user = User.find(params[:id])
    redirect_to @user unless @user == current_user
  end
  
  # Function deletes the current user and returns them to the root path #
  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      @user.destroy
      redirect_to root_path
    elsif  current_user.admin
      @user.destroy
      redirect_to users_path
    else
      redirect_to users_path
    end
  end

  # Creates an index of users to paginate #
  def index
    @users = User.paginate(page: params[:page])
  end
  
  # Gets a user based on params for show page #
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page])
    @projects = @user.projects.paginate(page: params[:page])
  end

  # Gets a user based on params for edit page #  
  def edit
    @user = User.find(params[:id])
    redirect_to @user unless @user == current_user
  end

  # Updates a user based on params from edit page #  
  ### NOTE NEED TO FIX HERE FOR PASSWORD PAGE### 
    #params.select {
   #   |param| [:name, :email, :twitter, :about_me, :interests].include? param
    #}
  def update
    @user = User.find(params[:id])
    if update_edit_attributes
      sign_in @user
      redirect_to @user
    else
    render 'edit'
    end
  end
  
  # Obvi brah, new instance brah #
  def new
    if signed_in?
      redirect_to current_user
    else
      @user = User.new
    end
  end
  
  # brooooahahah #
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Printless!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  
  private
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
  
  def update_edit_attributes
    thing = [:name, :image, :email, :twitter_id, :about_me]
    validity = true
    thing.each do |attribute|
      if @user.update_attribute(attribute, params[:user][attribute])
        validity = true && validity
      else
        validity = false && validity
      end
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
				remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_header.html.erb
<% if !current_user.nil? %>
	<div id="navsection">
	<ul id="nav">
		<li class="taba" id="tab1">
			<%= link_to "My Profile", current_user %>
		</li>
		<% if @user == current_user %> 
		<li class="taba" id="tab2">
			<%= link_to 'New Article', new_article_path %>
		</li>	
		<% end %>
		<li class="tabb" id="tab3">
			<%= link_to "Edit Profile", edit_user_path(current_user) %>
		</li>	
		<li class="tabb" id="tab4">
			<%= link_to "About Us", about_path %>
		</li>
		<li class="tabb" id="tab5">
			<a href="#">Give feedback</a>
		</li>
		<li class="tabb" id="tab6">
			<%= link_to "Sign Out", signout_path %>
		</li>
	</ul>
</div>
<% end %>

app/views/users/_my_articles.html.erb
<div class="myarticles">
	<h1>Recent Work</h1>
	<ul class="articlelist">
		<div id="paginate_top">
		<%= will_paginate @articles %>
		</div>
		<% if @user.articles.any? %>
		<% @articles.each do |article| %>
			<li class="article">
				<h1 class="articletitle"><%= link_to article.title, article %></h1>
				<div class="articlepict"></div>
				<p><%= article.content %></p>
				<ul class="articleinfo">
					<li class="byline"><span class="by">by</span>
						<%= link_to @user.name, @user, :class => "author" %>
					</li>
					<li class="date"><span id="topdate"> 
						<%= article.created_at.to_date %></span>
					</li>
					<li class="comments"><a href="#"><span
						id="commentno1">10</span></a></li>
					</ul>
			</li>
  		<% end %>
		<% end %>
		<div id="paginate_bottom">
		<%= will_paginate @articles %>
		</div>
	</ul>
</div>

app/views/users/_my_projects.html.erb
<div class="myprojects">
	<h1>Projects</h1>
	<ul class="projects">
		<% if @user.projects.any? %>
		<%= will_paginate @projects %>
		<% @projects.each do |project| %>
		<li>
			<h1><%= link_to project.title, project %></h1>
			<p><%= project.content %></p>
			<ul class="moneystuff">
				<li class="goal">
					<h2>Goal:</h2> <%= project.money_wanted %></li>
				<li class="amount_raised">
					<h2>Raised so far:</h2> <%= project.money_earned %></li>
			</ul>
    	</li>
  	<% end %>
<% end %>
</ul>
</div>

app/views/users/_stylesheets.html.erb
<%= stylesheet_link_tag 'signup', :media => 'all' %>
<%= stylesheet_link_tag 'users', :media => 'all' %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
			 remote: true) do |f| %>
  <%= f.submit "Unfollow", :class => "btn btn-large" %>
<% end %>

app/views/users/change_password.html.erb
<% provide :title, "Change Password" %> 
<h1>Change Password</h1>

<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide :title, "Edit user" %> 
<h1>Edit user</h1>

<%= form_for @user, :html => { :multipart => true } do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :image %><br />
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter_id %><br />
    <%= f.text_field :twitter_id %>
  </div>
  <div class="field">
    <%= f.label :about_me %><br />
    <%= f.text_field :about_me %>
  </div>
  <div class="field">
    <%= f.label :interests %><br />
    <%= f.text_field :interests %>
  </div>
    <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to "Change Password", changepassword_path %>

app/views/users/index.html.erb
<div id="user_list">
<h1 id="all_users">All users</h1>
<div id="user_paginate_top">
<%= will_paginate %>
</div>

<ul class="users">
  <% @users.each do |user| %>
    <li> <%= link_to user.name, user %>
	  <% if current_user.admin? && !(current_user == user) %>
		<%= link_to "Delete", user, confirm: "Are you sure?", method: :delete %>
		<% end %>
    </li><br/><br/>
  <% end %>
</ul>
<div id="user_paginate_bottom">
<%= will_paginate %>
</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="signupform">
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages' %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<div id="member">Already a member?
<%= link_to "sign in", signin_path %>
</div>
</div>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="content">
  <div id="topcontent">
    <div class="profileinfo">
    <h1 id="name"> <%= @user.name %> </h1>

      <div class="profilepict" id="michael_desa_picture">
      <%= image_tag @user.image_url %>
      </div>

      <div class="about">
       <div class="aboutword">About</div> <p><%= @user.about_me %> </p>
      </div>

    <%= render '/shared/stats' %>
    <%= render 'follow_form' if signed_in? %>
    </div>
    <%= render 'users/my_projects' %>
  </div>
    <%= render 'users/my_articles' %>
</div>

app/views/users/show_follow.html.erb
<div class="sure">
  <aside class="okay4">
    <section>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span><br/>
      <span><b>Articles:</b> <%= @user.articles.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
      <% end %>
    </section>
  </aside>
  <div class="okay8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
		<% @users.each do |user| %>
			<%= link_to user.name, user %><br/>
			<% end %>
      </ul>
      <%= will_paginate @users %>
    <% end %>
  </div>
</div>