config/routes.rb
Printless::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles, has_many: :comments
  resources :projects, has_many: :comments
  resources :relationships, only: [:create, :destroy]
  resources :invitation_lists, only: [:new, :create]
  

  match '/changepassword', to: 'users#change_password'
  #Change back for live version
  match '/signup',  to: 'users#new'
  #match '/signup', to: 'invitation_lists#temphome'
  match '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  match '/contact', to: 'mostly_static_pages#contact'
  match '/about', to: 'mostly_static_pages#about'

  root :to => 'invitation_lists#temphome'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :content, :money_wanted
  belongs_to :user
  
  has_many :comments, as: :commentable, dependent: :destroy
  
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true
  validates :user_id, presence: true
  validates :money_wanted, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   before_filter :signed_in_user, only: [:new, :create]
   before_filter :current_user, only: [:new, :create, :destroy]

  def index
     #@articles = Article.all
     @projects = Project.paginate(page: params[:page])
   end

   def show
     @project = Project.find(params[:id])
     @author = User.find(@project.user_id)
     @comments = @project.comments.paginate(page: params[:page])
   end

   def new
     @project = current_user.projects.build(params[:project])
   end

   def edit
      @project = Project.find(params[:id])
      redirect_to @project unless current_user.id == @project.user_id
   end

   def create
     @project = current_user.projects.build(params[:project])
     if @project.save
       redirect_to @project
     else
       redirect_to root_path
     end
   end

     def update
       @project = Project.find(params[:id])
       if @project.update_attributes(params[:project])
         @project.save
         redirect_to @project
       else
       render 'edit'
     end
   end

   # Something doesnt work here #
   def destroy
     @project = Article.find(params[:id])
     if @project.user_id == current_user.id
       @project.destroy
       redirect_to user_path
     else
       @project.destroy
       redirect_to user_path
     end
   end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_header.html.erb
<div id="navsection">
	<ul id="nav">
		<li class="taba" id="tab1">
			<%= link_to "My Profile", current_user %>
		</li>
		<li class="taba" id="tab2">
			<%= link_to 'New Article', new_article_path %>
		</li>
		<li class="tabb" id="tab3">
			<%= link_to 'New Project', new_project_path %>
		</li>	
		<li class="tabb" id="tab4">
			<%= link_to "Edit Profile", edit_user_path(current_user) %>
		</li>	
		<li class="tabb" id="tab5">
			<a href="#">About</a>
		</li>
		<li class="tabb" id="tab6">
			<a href="#">Give us feedback</a>
		</li>
		<li class="tabb" id="tab7">
			<%= link_to "Sign Out", signout_path %>
		</li>
	</ul>
</div>

app/views/projects/_project.html.erb
<div class="project">
	<h1 class="projecttitle"><%= @project.title %></h1>
	<ul class = "projectinfo">
		<li class="byline"><span class="by">by</span>
		<%= link_to @author.name, @author, :class => "author" %></li>
		<li class="date"><span id="topdate">
		<%= @project.created_at %></span></li>
		<% if current_user == @author %>
			<li><%= link_to "Edit Project", edit_project_path,
					:class => "editproject" %></li>
		<% end %>
	</ul>
	
	 <p><%= @project.content %></p>
	
	<strong>Money Wanted:</strong><%= @project.money_wanted %><br/>
	<strong>Money Earned:</strong>
		<% if @project.money_earned == nil %>
			0
		<% else %>
			<%= @project.money_earned %>
		<% end %><br/>
	
	<% if current_user == @author %>
	<%= link_to "Edit Project", edit_project_path,
				:class => "editproject" %>
	<% end %>
	
</div>

<div id="projectabout">
	This is a preliminary view of your project. Only you can view this project at this time. When we are ready, your articles will be the first ones opened to the public.
	</div>

app/views/projects/_project_form.html.erb
<%= form_for(@project) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :money_wanted %><br />
    <%= f.number_field :money_wanted %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/projects/_stylesheets.html.erb
<%= stylesheet_link_tag 'projects', :media => 'all' %>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<%= will_paginate %>

<ul class="projects">
  <% @projects.each do |project| %>
    <li> <%= link_to User.find(project.user_id).name, User.find(project.user_id) %><br/>
	 	 <%= link_to project.title, project %><br/>
		 <%= project.content %></li><br/>
		Money Wanted: <%= project.money_wanted %><br/><br/>
  <% end %>
</ul>

<%= will_paginate %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render '/projects/project_form' %>

app/views/projects/show.html.erb
	<div id="firstcontent">
		<%= render 'project' %>
	</div>



	<strong>Comments</strong><br/>
		<%= render 'comments/comments' %>