config/routes.rb
Printless::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles, has_many: :comments
  resources :projects, has_many: :comments
  resources :relationships, only: [:create, :destroy]
  resources :invitation_lists, only: [:new, :create]
  

  match '/changepassword', to: 'users#change_password'
  #Change back for live version
  match '/signup',  to: 'users#new'
  #match '/signup', to: 'invitation_lists#temphome'
  match '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  match '/contact', to: 'mostly_static_pages#contact'
  match '/about', to: 'mostly_static_pages#about'

  root :to => 'invitation_lists#temphome'
end

app/controllers/mostly_static_pages_controller.rb
class MostlyStaticPagesController < ApplicationController
end

app/helpers/mostly_static_pages_helper.rb
module MostlyStaticPagesHelper
end

app/views/mostly_static_pages/_header.html.erb
<div id="navsection">
	<ul id="nav">
		<li class="taba" id="tab1">
			<%= link_to "My Profile", current_user %>
		</li>
		<% if @user == current_user %> 
		<li class="taba" id="tab2">
			<%= link_to 'New Article', new_article_path %>
		</li>
		<li class="tabb" id="tab3">
			<%= link_to 'New Project', new_project_path %>
		</li>	
		<% end %>
		<li class="tabb" id="tab4">
			<%= link_to "Edit Profile", edit_user_path(current_user) %>
		</li>	
		<li class="tabb" id="tab5">
			<%= link_to "About Us", about_path %>
		</li>
		<li class="tabb" id="tab6">
			<a href="#">Give us feedback</a>
		</li>
		<li class="tabb" id="tab7">
			<%= link_to "Sign Out", signout_path %>
		</li>
	</ul>
</div>

app/views/mostly_static_pages/_stylesheets.html.erb
<%= stylesheet_link_tag 'mostly_static_pages', :media => 'all' %>

app/views/mostly_static_pages/about.html.erb
<% provide :title, 'About The Printless' %>
<div class="about">
	The Printless is a adsfsdkfjdskfldjsldfdskf
</div>

app/views/mostly_static_pages/contact.html.erb
<% provide :title, 'Contact' %>
<div class="contact">
	Contact: <a href="mailto:hello@theprintless.com">hello@theprintless.com</a>
</div>

app/views/mostly_static_pages/stylesheets.html.erb
<%= stylesheet_link_tag 'mostly_static_pages', :media => 'all' %>