config/routes.rb
Printless::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles, has_many: :comments
  resources :projects, has_many: :comments
  resources :relationships, only: [:create, :destroy]
  resources :invitation_lists, only: [:new, :create]
  

  match '/changepassword', to: 'users#change_password'
  #Change back for live version
  match '/signup',  to: 'users#new'
  #match '/signup', to: 'invitation_lists#temphome'
  match '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete

  match '/contact', to: 'mostly_static_pages#contact'
  match '/about', to: 'mostly_static_pages#about'

  root :to => 'invitation_lists#temphome'
end

app/views/layouts/_footer.html.erb
<div id="footer1">
  <nav class="round">
    <ul>
      <li><%= link_to "About Us", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
	  <% unless signed_in? %>
	  <li><%= link_to "Sign up", signup_path %></li>
	  <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
		<li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<li><%= link_to "Delete Account", current_user,
					   confirm: "Are you sure?", method: :delete %></li>
      <% end %>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path%></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_header1.html.erb
<div class="header1">
		<div class="logo">
			<a id="blackandredlargelogo" href="">
				<%= image_tag('pllogoblackandred42px.png')%></a>
		</div>
		<ul class="social" id="sociallinks">
				<li><a id="twitter" href="https://twitter.com/#!/thePrintless">
					Twitter</a></li>
				<li><a id="fb" href="https://www.facebook.com">
					Facebook</a></li>
		</ul>
</div>

<%= render 'header' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'stylesheets' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	<link href='http://fonts.googleapis.com/css?family=Questrial'
		rel='stylesheet'type='text/css'>
  </head>
  <body>
	
	<div class="outercontainer">
	</div>
	
    <div class="container">
      <%= render 'layouts/header1' %>

        <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/layouts/invitation_list.html.erb
<!DOCTYPE HTML>
<html>

<head>
    <title>Printless</title>
    <%= render 'layouts/stylesheets' %>
	<%= stylesheet_link_tag "invitation_list", :media => "all" %>
	
	<%= stylesheet_link_tag "signupstyle", :media => "all" %>
	
	<%= stylesheet_link_tag "temp_homepage", :media => "all" %>
	
    <%= javascript_include_tag "temp_homepage" %>
    <%= csrf_meta_tags %>

</head>

<body>
	
	<div id="contentwrapper">
	<div class="container">
		<%= render 'invitation_lists/header' %>
		<div id='signin'>
		<%= render 'invitation_lists/signin'%>
		</div>
	<div class="content">
		<%= render 'invitation_lists/content' %>
	</div>
</div>
</div>	
</body>